name: flutter_application_2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2

  cupertino_icons: ^1.0.8

  google_fonts: ^6.2.1
  firebase_core: ^2.30.0
  firebase_auth: ^4.17.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  # flutter_local_notifications: ^17.1.0
  timezone: ^0.10.1
  firebase_core: ^2.0.0
  firebase_auth: ^4.0.0
  cloud_firestore: ^4.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/ROS_Logo.png"
  adaptive_icon_foreground: "assets/icons/ROS_Logo_foreground.png"
  adaptive_icon_background: "#ffffff" # hexcode for background color

  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icons/ROS_Logo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icons/ROS_Logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icons/ROS_Logo.png"
    
flutter:
  uses-material-design: true

  assets:
    - assets/images/login_background.jpg
    - assets/images/Badminton Court.png
    - assets/images/Table Tennis.png
    - assets/images/Tennis Court.png
    - assets/icons/ROS_Logo-new.png
    
  fonts:
    - family: BebasNeue
      fonts:
        - asset: assets/fonts/BebasNeue-Regular.ttf
    - family: Bebasneuecyrillic
      fonts:
        - asset: assets/fonts/bebasneuecyrillic.ttf
    - family: GlacialIndifference
      fonts:
        - asset: assets/fonts/GlacialIndifference-Regular.otf
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf


  
