// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWNb006CNbxndseOWYlL4iSpZUnnMYHyA',
    appId: '1:1024478374733:web:ea1114898e6a0f0de2e504',
    messagingSenderId: '1024478374733',
    projectId: 'ros-app-eng4001',
    authDomain: 'ros-app-eng4001.firebaseapp.com',
    storageBucket: 'ros-app-eng4001.firebasestorage.app',
    measurementId: 'G-XGLHZRX9SM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBu5BEY3qbPZ2sweuhT5vr-obGfNSrjUhA',
    appId: '1:1024478374733:android:76aad8526a2cdbcce2e504',
    messagingSenderId: '1024478374733',
    projectId: 'ros-app-eng4001',
    storageBucket: 'ros-app-eng4001.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDdOKpQwaphFt38o6G7yRYhRCunr5s144',
    appId: '1:1024478374733:ios:6ca732e4308620b9e2e504',
    messagingSenderId: '1024478374733',
    projectId: 'ros-app-eng4001',
    storageBucket: 'ros-app-eng4001.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDdOKpQwaphFt38o6G7yRYhRCunr5s144',
    appId: '1:1024478374733:ios:6ca732e4308620b9e2e504',
    messagingSenderId: '1024478374733',
    projectId: 'ros-app-eng4001',
    storageBucket: 'ros-app-eng4001.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWNb006CNbxndseOWYlL4iSpZUnnMYHyA',
    appId: '1:1024478374733:web:c31c0bcae9d0225be2e504',
    messagingSenderId: '1024478374733',
    projectId: 'ros-app-eng4001',
    authDomain: 'ros-app-eng4001.firebaseapp.com',
    storageBucket: 'ros-app-eng4001.firebasestorage.app',
    measurementId: 'G-VGGXPG3WQ7',
  );
}